# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "httpthumbnailer"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jakub Pastuszek"]
  s.date = "2013-07-16"
  s.description = "Provides HTTP API for thumbnailing images"
  s.email = "jpastuszek@gmail.com"
  s.executables = ["httpthumbnailer"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/httpthumbnailer",
    "features/httpthumbnailer.feature",
    "features/step_definitions/httpthumbnailer_steps.rb",
    "features/support/env.rb",
    "features/support/test-large.jpg",
    "features/support/test-transparent.png",
    "features/support/test.jpg",
    "features/support/test.png",
    "features/support/test.txt",
    "features/thumbnail.feature",
    "features/thumbnails.feature",
    "httpthumbnailer.gemspec",
    "lib/httpthumbnailer/error_reporter.rb",
    "lib/httpthumbnailer/plugin/thumbnailer.rb",
    "lib/httpthumbnailer/thumbnail_specs.rb",
    "lib/httpthumbnailer/thumbnailer.rb",
    "load_test/extralarge.jpg",
    "load_test/large.jpg",
    "load_test/large.png",
    "load_test/load_test-cd9679c.csv",
    "load_test/load_test-v0.3.1.csv",
    "load_test/load_test.jmx",
    "load_test/medium.jpg",
    "load_test/small.jpg",
    "load_test/soak_test-ac0c6bcbe5e-broken-libjpeg-tatoos.csv",
    "load_test/soak_test-cd9679c.csv",
    "load_test/soak_test-f98334a-tatoos.csv",
    "load_test/soak_test.jmx",
    "load_test/tiny.jpg",
    "load_test/v0.0.13-loading.csv",
    "load_test/v0.0.13.csv",
    "load_test/v0.0.14-no-optimization.csv",
    "load_test/v0.0.14.csv",
    "spec/image_processing_spec.rb",
    "spec/spec_helper.rb",
    "spec/thumbnail_specs_spec.rb"
  ]
  s.homepage = "http://github.com/jpastuszek/httpthumbnailer"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "HTTP thumbnailing server"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<unicorn-cuba-base>, ["~> 1.0"])
      s.add_runtime_dependency(%q<rmagick>, ["~> 2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.13"])
      s.add_development_dependency(%q<rspec-mocks>, ["~> 2.13"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<capybara>, ["~> 1.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<httpclient>, ["~> 2.3"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.9"])
      s.add_development_dependency(%q<multipart-parser>, ["~> 0.1.1"])
      s.add_development_dependency(%q<daemon>, ["~> 1.1"])
    else
      s.add_dependency(%q<unicorn-cuba-base>, ["~> 1.0"])
      s.add_dependency(%q<rmagick>, ["~> 2"])
      s.add_dependency(%q<rspec>, ["~> 2.13"])
      s.add_dependency(%q<rspec-mocks>, ["~> 2.13"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<capybara>, ["~> 1.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<httpclient>, ["~> 2.3"])
      s.add_dependency(%q<rdoc>, ["~> 3.9"])
      s.add_dependency(%q<multipart-parser>, ["~> 0.1.1"])
      s.add_dependency(%q<daemon>, ["~> 1.1"])
    end
  else
    s.add_dependency(%q<unicorn-cuba-base>, ["~> 1.0"])
    s.add_dependency(%q<rmagick>, ["~> 2"])
    s.add_dependency(%q<rspec>, ["~> 2.13"])
    s.add_dependency(%q<rspec-mocks>, ["~> 2.13"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<capybara>, ["~> 1.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<httpclient>, ["~> 2.3"])
    s.add_dependency(%q<rdoc>, ["~> 3.9"])
    s.add_dependency(%q<multipart-parser>, ["~> 0.1.1"])
    s.add_dependency(%q<daemon>, ["~> 1.1"])
  end
end

